// <auto-generated />
using System;
using Amazon.Inventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amazon.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryContext))]
    partial class InventoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Amazon.Inventory.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("products", "inventory");
                });

            modelBuilder.Entity("Moamen.SDKs.SharedKernel.DDD.Events.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailureRetriesCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "inventory");
                });

            modelBuilder.Entity("Amazon.Inventory.Domain.Products.Product", b =>
                {
                    b.OwnsMany("Amazon.Inventory.Domain.Products.ValueObjects.ProductInventoryChange", "_inventoryChanges", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("After")
                                .HasColumnType("int");

                            b1.Property<int>("Before")
                                .HasColumnType("int");

                            b1.Property<DateTime>("OccurredOn")
                                .HasColumnType("datetime2");

                            b1.HasKey("ProductId", "Id");

                            b1.ToTable("inventoryChanges", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("Amazon.Inventory.Domain.Products.ValueObjects.ProductInventory", "Inventory", b1 =>
                        {
                            b1.Property<Guid>("ProductId1")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("ProductId1");

                            b1.ToTable("products", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("ProductId1");

                            b1.OwnsMany("Amazon.Inventory.Domain.Products.Entities.InventoryItem", "Items", b2 =>
                                {
                                    b2.Property<Guid>("ProductId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("CreatedBy")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.Property<DateTime>("CreatedOn")
                                        .HasColumnType("datetime2");

                                    b2.Property<Guid?>("ReservedForOrder")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("UpdatedBy")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.Property<DateTime?>("UpdatedOn")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("ProductId", "Id");

                                    b2.ToTable("inventoryItems", "inventory");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductId");
                                });

                            b1.Navigation("Items");
                        });

                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("_inventoryChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
