// <auto-generated />
using System;
using Amazon.Customers.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amazon.Customers.Infrastructure.Migrations
{
    [DbContext(typeof(CustomersContext))]
    [Migration("20260509120004_Add_Customers_With_Shipping_Address")]
    partial class Add_Customers_With_Shipping_Address
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Amazon.Customers.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Amazon.Customers.Domain.Customer", b =>
                {
                    b.OwnsOne("Amazon.Customers.Domain.ValueObjects.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("Amazon.Customers.Domain.ValueObjects.ShippingInfo", "ShippingInfo", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.OwnsMany("Amazon.Customers.Domain.Entities.ShippingAddress", "ShippingAddresses", b2 =>
                                {
                                    b2.Property<Guid>("CustomerId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("CreatedBy")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.Property<DateTime>("CreatedOn")
                                        .HasColumnType("datetime2");

                                    b2.Property<bool>("IsDefault")
                                        .HasColumnType("bit");

                                    b2.Property<string>("UpdatedBy")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.Property<DateTime?>("UpdatedOn")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("CustomerId", "Id");

                                    b2.ToTable("ShippingAddress");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerId");

                                    b2.OwnsOne("Amazon.Customers.Domain.ValueObjects.CityInfo", "City", b3 =>
                                        {
                                            b3.Property<Guid>("ShippingAddressCustomerId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<int>("ShippingAddressId")
                                                .HasColumnType("int");

                                            b3.Property<int>("CityId")
                                                .HasColumnType("int");

                                            b3.Property<int>("CountryId")
                                                .HasColumnType("int");

                                            b3.Property<string>("PostalCode")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.HasKey("ShippingAddressCustomerId", "ShippingAddressId");

                                            b3.ToTable("ShippingAddress");

                                            b3.WithOwner()
                                                .HasForeignKey("ShippingAddressCustomerId", "ShippingAddressId");
                                        });

                                    b2.OwnsOne("Amazon.Customers.Domain.ValueObjects.HouseInfo", "House", b3 =>
                                        {
                                            b3.Property<Guid>("ShippingAddressCustomerId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<int>("ShippingAddressId")
                                                .HasColumnType("int");

                                            b3.Property<int?>("ApartmentNumber")
                                                .HasColumnType("int");

                                            b3.Property<int>("BuildingNumber")
                                                .HasColumnType("int");

                                            b3.Property<string>("Street")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.HasKey("ShippingAddressCustomerId", "ShippingAddressId");

                                            b3.ToTable("ShippingAddress");

                                            b3.WithOwner()
                                                .HasForeignKey("ShippingAddressCustomerId", "ShippingAddressId");
                                        });

                                    b2.Navigation("City")
                                        .IsRequired();

                                    b2.Navigation("House")
                                        .IsRequired();
                                });

                            b1.Navigation("ShippingAddresses");
                        });

                    b.Navigation("ContactInfo")
                        .IsRequired();

                    b.Navigation("ShippingInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
