// <auto-generated />
using System;
using System.Collections.Generic;
using Amazon.Orders.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amazon.Orders.Infrastructure.Migrations
{
    [DbContext(typeof(OrdersContext))]
    [Migration("20260610104608_Drop_Outbox_Temp")]
    partial class Drop_Outbox_Temp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Amazon.Orders.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.ComplexProperty<Dictionary<string, object>>("Owner", "Amazon.Orders.Domain.Orders.Order.Owner#CustomerInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("orders", "orders");
                });

            modelBuilder.Entity("Amazon.Orders.Domain.Orders.ValueObjects.Status.OrderStatusChange", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "Id");

                    b.ToTable("statusHistory", "orders");

                    b.HasDiscriminator().HasValue("OrderStatusChange");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Amazon.Orders.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InStockCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("products", "orders");
                });

            modelBuilder.Entity("Amazon.Orders.Domain.Stakeholders.StakeHolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StakeHolder");

                    b.HasDiscriminator().HasValue("StakeHolder");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Amazon.Orders.Domain.Orders.ValueObjects.Status.OrderCancelledStatus", b =>
                {
                    b.HasBaseType("Amazon.Orders.Domain.Orders.ValueObjects.Status.OrderStatusChange");

                    b.HasDiscriminator().HasValue("OrderCancelledStatus");
                });

            modelBuilder.Entity("Amazon.Orders.Domain.Orders.ValueObjects.Status.OrderDeliveredStatus", b =>
                {
                    b.HasBaseType("Amazon.Orders.Domain.Orders.ValueObjects.Status.OrderStatusChange");

                    b.HasDiscriminator().HasValue("OrderDeliveredStatus");
                });

            modelBuilder.Entity("Amazon.Orders.Domain.Orders.ValueObjects.Status.OrderDeliveryRecievedStatus", b =>
                {
                    b.HasBaseType("Amazon.Orders.Domain.Orders.ValueObjects.Status.OrderStatusChange");

                    b.HasDiscriminator().HasValue("OrderDeliveryRecievedStatus");
                });

            modelBuilder.Entity("Amazon.Orders.Domain.Orders.ValueObjects.Status.OrderPendingStatus", b =>
                {
                    b.HasBaseType("Amazon.Orders.Domain.Orders.ValueObjects.Status.OrderStatusChange");

                    b.HasDiscriminator().HasValue("OrderPendingStatus");
                });

            modelBuilder.Entity("Amazon.Orders.Domain.Orders.ValueObjects.Status.OrderProcessingStatus", b =>
                {
                    b.HasBaseType("Amazon.Orders.Domain.Orders.ValueObjects.Status.OrderStatusChange");

                    b.HasDiscriminator().HasValue("OrderProcessingStatus");
                });

            modelBuilder.Entity("Amazon.Orders.Domain.Orders.ValueObjects.Status.OrderShippedStatus", b =>
                {
                    b.HasBaseType("Amazon.Orders.Domain.Orders.ValueObjects.Status.OrderStatusChange");

                    b.Property<string>("TrackingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("OrderShippedStatus");
                });

            modelBuilder.Entity("Amazon.Orders.Domain.Orders.ValueObjects.Status.OrderShippingStartedStatus", b =>
                {
                    b.HasBaseType("Amazon.Orders.Domain.Orders.ValueObjects.Status.OrderStatusChange");

                    b.HasDiscriminator().HasValue("OrderShippingStartedStatus");
                });

            modelBuilder.Entity("Amazon.Orders.Domain.Stakeholders.AdminUser", b =>
                {
                    b.HasBaseType("Amazon.Orders.Domain.Stakeholders.StakeHolder");

                    b.HasDiscriminator().HasValue("AdminUser");
                });

            modelBuilder.Entity("Amazon.Orders.Domain.Stakeholders.Customer", b =>
                {
                    b.HasBaseType("Amazon.Orders.Domain.Stakeholders.StakeHolder");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("Amazon.Orders.Domain.Stakeholders.DeliveryUser", b =>
                {
                    b.HasBaseType("Amazon.Orders.Domain.Stakeholders.StakeHolder");

                    b.HasDiscriminator().HasValue("DeliveryUser");
                });

            modelBuilder.Entity("Amazon.Orders.Domain.Orders.Order", b =>
                {
                    b.OwnsMany("Amazon.Orders.Domain.Orders.ValueObjects.OrderItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("OrderId", "Id");

                            b1.ToTable("orderItems", "orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("Amazon.Orders.Domain.Orders.ValueObjects.ProductInfo", "ProductInfo", b2 =>
                                {
                                    b2.Property<Guid>("OrderItemOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("OrderItemId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<Guid>("ProductId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("UnitPrice")
                                        .HasColumnType("decimal(18,2)");

                                    b2.HasKey("OrderItemOrderId", "OrderItemId");

                                    b2.ToTable("orderItems", "orders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderItemOrderId", "OrderItemId");
                                });

                            b1.Navigation("ProductInfo")
                                .IsRequired();
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Amazon.Orders.Domain.Orders.ValueObjects.Status.OrderStatusChange", b =>
                {
                    b.HasOne("Amazon.Orders.Domain.Orders.Order", null)
                        .WithMany("_history")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Amazon.Orders.Domain.Orders.ValueObjects.Status.OrderDeliveryRecievedStatus", b =>
                {
                    b.OwnsOne("Amazon.Orders.Domain.Orders.ValueObjects.Status.DeliveryMember", "DeliveryMember", b1 =>
                        {
                            b1.Property<Guid>("OrderDeliveryRecievedStatusOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("OrderDeliveryRecievedStatusId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrderDeliveryRecievedStatusOrderId", "OrderDeliveryRecievedStatusId");

                            b1.ToTable("statusHistory", "orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderDeliveryRecievedStatusOrderId", "OrderDeliveryRecievedStatusId");
                        });

                    b.Navigation("DeliveryMember")
                        .IsRequired();
                });

            modelBuilder.Entity("Amazon.Orders.Domain.Orders.ValueObjects.Status.OrderShippingStartedStatus", b =>
                {
                    b.OwnsOne("Amazon.Orders.Domain.Orders.ValueObjects.Status.ShippingCompanyInfo", "CompanyInfo", b1 =>
                        {
                            b1.Property<Guid>("OrderShippingStartedStatusOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("OrderShippingStartedStatusId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Website")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrderShippingStartedStatusOrderId", "OrderShippingStartedStatusId");

                            b1.ToTable("statusHistory", "orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderShippingStartedStatusOrderId", "OrderShippingStartedStatusId");
                        });

                    b.Navigation("CompanyInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Amazon.Orders.Domain.Orders.Order", b =>
                {
                    b.Navigation("_history");
                });
#pragma warning restore 612, 618
        }
    }
}
