<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="MassTransit" Version="8.3.5" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="8.3.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Amazon.Orders.Domain\Amazon.Orders.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Moamen.SDKs.Repository">
			<HintPath>..\..\lib\Moamen.SDKs.Repository.dll</HintPath>
		</Reference>
		<Reference Include="Moamen.SDKs.SharedKernel">
			<HintPath>..\..\lib\Moamen.SDKs.SharedKernel.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>
