<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared-kernel\Amazon.SharedKernel\Amazon.SharedKernel.csproj" />
    <ProjectReference Include="..\Amazon.Shipping.Domain\Amazon.Shipping.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Moamen.SDKs.Repository">
      <HintPath>..\..\identity-management\lib\Moamen.SDKs.Repository.dll</HintPath>
    </Reference>
    <Reference Include="Moamen.SDKs.SharedKernel">
      <HintPath>..\..\..\..\..\Moamen.Lookups\lib\Moamen.SDKs.SharedKernel.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
