<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Duende.IdentityServer.AspNetIdentity" version="7.2.0" />
		<PackageReference Include="MassTransit" Version="8.3.5" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="8.3.5" />

		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.11" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />

		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\shared-kernel\Amazon.SharedKernel\Amazon.SharedKernel.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="Moamen.SDKs.Repository">
	    <HintPath>..\lib\Moamen.SDKs.Repository.dll</HintPath>
	  </Reference>
	</ItemGroup>
</Project>
