<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared-kernel\Amazon.SharedKernel\Amazon.SharedKernel.csproj" />
    <ProjectReference Include="..\Amazon.ProductCatalog.Domain\Amazon.ProductCatalog.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="EMP.SharedKernel">
      <HintPath>..\..\..\..\..\07-My Work\03- SURE\0-Projects\NCNP\EMP.SharedKernel\obj\Debug\net8.0\EMP.SharedKernel.dll</HintPath>
    </Reference>
    <Reference Include="Moamen.SDKs.Repository">
      <HintPath>..\..\..\..\..\02- Developer\08-My SDKs\Moamen.SDKs\Moamen.SDKs.Repository\bin\Release\net9.0\Moamen.SDKs.Repository.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
