<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.3.5" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared-kernel\Amazon.SharedKernel\Amazon.SharedKernel.csproj" />
    <ProjectReference Include="..\Amazon.ProductCatalog.Domain\Amazon.ProductCatalog.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Moamen.SDKs.Repository">
      <HintPath>..\..\..\..\..\02- Developer\08-My SDKs\Moamen.SDKs\Moamen.SDKs.Repository\bin\Release\net9.0\Moamen.SDKs.Repository.dll</HintPath>
    </Reference>
    <Reference Include="Moamen.SDKs.SharedKernel">
      <HintPath>..\..\..\..\..\02- Developer\08-My SDKs\Moamen.SDKs\Moamen.SDKs.SharedKernel\bin\Release\net9.0\Moamen.SDKs.SharedKernel.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
