<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Amazon.Orders.Application\Amazon.Orders.Application.csproj" />
    <ProjectReference Include="..\Amazon.Orders.Infrastructure\Amazon.Orders.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Moamen.SDKs.Repository">
      <HintPath>..\..\..\..\..\02- Developer\08-My SDKs\Moamen.SDKs\Moamen.SDKs.SharedKernel\bin\Debug\net9.0\Moamen.SDKs.Repository.dll</HintPath>
    </Reference>
    <Reference Include="Moamen.SDKs.SharedKernel">
      <HintPath>..\..\..\..\..\02- Developer\08-My SDKs\Moamen.SDKs\Moamen.SDKs.SharedKernel\bin\Debug\net9.0\Moamen.SDKs.SharedKernel.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
