<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Configurations\**" />
    <Compile Remove="Migrations\**" />
    <EmbeddedResource Remove="Configurations\**" />
    <EmbeddedResource Remove="Migrations\**" />
    <None Remove="Configurations\**" />
    <None Remove="Migrations\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Data\ShoppingCartContext.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Amazon.Cart.Domain\Amazon.Cart.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.34.1" />
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.80.0" />
    <PackageReference Include="Grpc.Tools" Version="2.80.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Moamen.SDKs.Repository">
      <HintPath>..\..\..\..\..\02- Developer\08-My SDKs\Moamen.SDKs\Moamen.SDKs.SharedKernel\bin\Release\net9.0\Moamen.SDKs.Repository.dll</HintPath>
    </Reference>
    <Reference Include="Moamen.SDKs.SharedKernel">
      <HintPath>..\..\..\..\..\02- Developer\08-My SDKs\Moamen.SDKs\Moamen.SDKs.SharedKernel\bin\Release\net9.0\Moamen.SDKs.SharedKernel.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Protos\" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\inventory\Amazon.Inventory.Grpc\Protos\product.proto" GrpcServices="Client">
      <Link>Protos\product.proto</Link>
    </Protobuf>
  </ItemGroup>

</Project>
